### ISSUE TITLE
Cannot run hamster-gtk 0.11.0 from PyPI

### ISSUE THREAD

**Issue by ThomasA** [projecthamster/hamster-gtk#229] opened 2018-10-29 13:37 UTC
I am using Ubuntu 18.04 and I am trying to install and run `hamster-gtk`.
I am using Ubuntu's supplied Python 2.7 and I have installed the dependencies listed for `hamster-gtk`. I am not installing it in a virtualenv, though. I simply installed it directly using `pip install hamster-gtk`.
Installation of both the dependencies and `hamster-gtk` completed without errors, but when I try to run it, I get the following error:

    $ .local/bin/hamster-gtk 
    Traceback (most recent call last):
      File ".local/bin/hamster-gtk", line 11, in <module>
        sys.exit(_main())
      File "/home/tha/.local/lib/python2.7/site-packages/hamster_gtk/hamster_gtk.py", line 389, in _main
        app = HamsterGTK()
      File "/home/tha/.local/lib/python2.7/site-packages/hamster_gtk/hamster_gtk.py", line 181, in __init__
        self._config = self._reload_config()
      File "/home/tha/.local/lib/python2.7/site-packages/hamster_gtk/hamster_gtk.py", line 238, in _reload_config
        config = self._get_config_from_file()
      File "/home/tha/.local/lib/python2.7/site-packages/hamster_gtk/hamster_gtk.py", line 383, in _get_config_from_file
        cp_instance = get_config_instance(get_fallback(), 'hamster-gtk', 'hamster-gtk.conf')
      File "/home/tha/.local/lib/python2.7/site-packages/hamster_gtk/helpers.py", line 127, in get_config_instance
        path = config_helpers.get_config_path(app_name, file_name)
      File "/home/tha/.local/lib/python2.7/site-packages/hamster_lib/helpers/config_helpers.py", line 155, in get_config_path
        return os.path.join(appdirs.user_config_dir, file_name)
    AttributeError: 'unicode' object has no attribute 'user_config_dir'

Any ideas what I could be doing wrong?

**Comment by jtojnar** [comment] 2018-10-29 17:43
Unfortunately, the latest version of hamster-gtk is not compatible with the latest hamster-lib. It was fixed in https://github.com/projecthamster/hamster-gtk/commit/aa55a047a244e6a3d9c656bc5e03ede8ba1b3115 but no release incorporates this fix yet.

**Comment by ThomasA** [comment] 2018-10-29 19:28
Ah OK, I think I will just stick to the https://github.com/ederag/hamster fork until that gets fixed then.

**Comment by dmytrokyrychuk** [comment] 2018-10-29 20:44
@ThomasA I have been using the latest version from git successfully: `pip install https://github.com/projecthamster/hamster-gtk/archive/develop.zip`

**Comment by ThomasA** [comment] 2018-10-29 20:51
Thanks @dmytrokyrychuk, I should give it a try.

**Comment by ThomasA** [comment] 2018-10-30 11:55
The development version does not really seem to work for me either. It complains that:

    $ ~/.local/bin/hamster-gtk
    Traceback (most recent call last):
      File "/home/tha/.local/bin/hamster-gtk", line 11, in <module>
        load_entry_point('hamster-gtk==0.11.0', 'gui_scripts', 'hamster-gtk')()
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
        return ep.load()
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
        return self.resolve()
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/home/tha/.local/lib/python2.7/site-packages/hamster_gtk/hamster_gtk.py", line 52, in <module>
        resources = Gio.resource_load(resources_path)
    GLib.Error: g-file-error-quark: Kunne ikke åbne filen “/home/tha/.local/lib/python2.7/site-packages/hamster_gtk/resources/hamster-gtk.gresource”: open() mislykkedes: Ingen sådan fil eller filkatalog (4)

The locale is Danish (da). The error message says:
> Could not open file “/home/tha/.local/lib/python2.7/site-packages/hamster_gtk/resources/hamster-gtk.gresource”: open() failed: No such file or folder (4)

I checked the path and there is indeed no such file present.

**Comment by jtojnar** [comment] 2018-10-30 12:14
Yes, when installing from git, the resources are not generated (make resources), see the AUR package comments: https://aur.archlinux.org/packages/python-hamster-gtk/

**Comment by dmytrokyrychuk** [comment] 2018-10-31 05:57
Sorry, @ThomasA. It's been a while since I installed hamster-gtk, totally forgot about this problem. If I remember correctly, you have to do the following:

```console
$ cd /home/tha/.local/lib/python2.7/site-packages/hamster_gtk/
$ make resources
```

You're going to need `glib-compile-resources` binary (`apt install libglib2.0-dev-bin` on Ubuntu).

**Comment by ThomasA** [comment] 2018-11-01 10:21
Hmm, that does not work. There are no makefiles in '/home/tha/.local/lib/python2.7/site-packages/hamster_gtk/' or any of its subfolders.

**Comment by jtojnar** [comment] 2018-11-01 10:24
Maybe you use newer version of Python than Dmytro?

**Comment by ThomasA** [comment] 2018-11-01 10:24
Does it have anything to do with [`glib-compile-resources`](https://developer.gnome.org/gio/stable/glib-compile-resources.html)? Just a wild guess. I cannot find any XML files either that could look like they have anything to do with that.

**Comment by ThomasA** [comment] 2018-11-01 10:25
I am using Ubuntu 18.04's standard version 2.7 of Python in this environment:

    $ python --version
    Python 2.7.15rc1

**Comment by ThomasA** [comment] 2018-11-01 10:26
Besides, how would a different version of Python explain that a file seems to be missing?

**Comment by jtojnar** [comment] 2018-11-01 10:31
If you installed hamster-gtk with Python 3 pip, it would go to a different directory.

Are you sure you are installing the zipball? Try to remove the directory and install it again to be sure.

**Comment by jtojnar** [comment] 2018-11-01 10:34
Yes, the error is caused by a missing `gresource` file, which would be produced by `glib-compile-resources` invoked by `make resources`

**Comment by ThomasA** [comment] 2018-11-01 10:35
Should I have installed and run it using Python 3 instead?

**Comment by ThomasA** [comment] 2018-11-01 10:49
I have now installed and attempted to run hamster using Python 3 instead.
Verification of version:

    $ python --version
    Python 3.6.6

Install:

    $ pip install https://github.com/projecthamster/hamster-gtk/archive/develop.zip
    
    ...
    
    Successfully installed appdirs-1.4.3 configparser-3.5.0 future-0.17.1 hamster-gtk-0.11.0 hamster-lib-0.13.2 icalendar-4.0.3 orderedset-2.0.1 python-dateutil-2.7.5 pytz-2018.7 six-1.11.0 sqlalchemy-1.2.13

Run:

    $ .local/bin/hamster-gtk 
    Traceback (most recent call last):
      File ".local/bin/hamster-gtk", line 11, in <module>
        load_entry_point('hamster-gtk==0.11.0', 'gui_scripts', 'hamster-gtk')()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
        return ep.load()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
        return self.resolve()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/home/tha/.local/lib/python3.6/site-packages/hamster_gtk/hamster_gtk.py", line 52, in <module>
        resources = Gio.resource_load(resources_path)
    GLib.Error: g-file-error-quark: Kunne ikke åbne filen “/home/tha/.local/lib/python3.6/site-packages/hamster_gtk/resources/hamster-gtk.gresource”: open() mislykkedes: Ingen sådan fil eller filkatalog (4)

Same error as for Python 2.7. And we can see from the output above that I have indeed installed and am running a separate hamster in '/home/tha/.local/lib/python3.6/site-packages/hamster_gtk/' now.

**Comment by jtojnar** [comment] 2018-11-01 10:53
Not sure what the error is then, python packaging is not really my thing. You can try to extract the zipball somewhere and run `make resources` there. That should definitely have the `Makefile`. Then you should be able to install it with `pip install .`, I think.

**Comment by ThomasA** [comment] 2018-11-01 11:02
Yes, the zip file does contain the resources. For some reason they never get unpacked correctly to the install folder, by either Python 2.7 pip or Python 3.6 pip.
I have managed to solve the problem now by manually extracting the 'hamster_gtk/resources' sub-folder and placing it in '/home/tha/.local/lib/python3.6/site-packages/hamster_gtk/'. Afterwards I run  `glib-compile-resources` on the contained 'hamster-gtk.gresource.xml'. Then it works and I can start Hamster.
Given the current state of the UI, I prefer to keep using the [https://github.com/ederag/hamster](https://github.com/ederag/hamster) fork so far.

**Closed as completed** 2018-11-01 11:48 UTC
